name: instrument-cookbooks-dev
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - arm_pyart
  - matplotlib
  - jupyterlab
  - cartopy
  - numpy
  - dask
  - distributed
  - xarray
  - pandas<2.0
  - fiona
  - pip
  - pip:
    - -r doc-requirements.txt
    - ambient-api
