name: instrument-cookbooks-dev
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - arm_pyart
  - act-atmos
  - matplotlib
  - jupyterlab
  - cartopy
  - numpy
  - dask
  - distributed
  - xarray
  - pandas<2.0
  - fiona
  - hvplot
  - imageio
  - pip
  - pip:
    - -r doc-requirements.txt
    - ambient-api
    - sage-data-client
    - nexradaws
    - sphinxcontrib-applehelp==1.0.7
    - sphinxcontrib-devhelp==1.0.5
    - sphinxcontrib-htmlhelp==2.0.4
    - sphinxcontrib-qthelp==1.0.6
    - sphinxcontrib-serializinghtml==1.1.9
